name: Local
variables:
  - name: interviewId
    value: ""
  - name: resumeId
    value: cmt2vgia40000h01zsmli11jt
  - secret: true
    name: BASE_URL
  - secret: true
    name: accessToken
  - secret: true
    name: jobId
