name: Local
variables:
  - secret: true
    name: BASE_URL
  - secret: true
    name: accessToken
  - secret: true
    name: jobId
  - name: interviewId
    value: ""
  - name: resumeId
    value: ""
